apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate-service
  template:
    metadata:
      labels:
        app: candidate-service
    spec:
      containers:
        - name: candidate-service
          image: candidate-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: candidate-service
spec:
  selector:
    app: candidate-service
  ports:
    - port: 8082
      targetPort: 8082
